FROM centos:6

MAINTAINER m.m.a.schenk@tudelft.nl

RUN yum -y install python-setuptools tar
RUN easy_install pip
RUN pip install virtualenv
RUN cd / && virtualenv virtual
RUN /virtual/bin/pip install supervisor
RUN mkdir /var/log/supervisor /etc/supervisor /etc/supervisor/conf.d

ADD supervisord.conf /etc/supervisord.conf

CMD [ "/virtual/bin/supervisord", "-n" ]
#CMD /bin/bash



